name: g-fortress

services:
  api:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: fastapi-application
    environment:
      PORT: 8000
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
  node:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
      target: dev
    working_dir: /app
    tty: true
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: sh -lc "corepack enable || true; tail -f /dev/null"
    ports:
      - "5173:5173"

  web:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
      target: nginx
    ports:
      - "80:80"
    # Only started when explicitly enabling the prod profile
    profiles: ["prod"]

  neo4j:
    image: neo4j:5.26
    container_name: neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/Test123456789!
    ports:
      - "7474:7474" # Web Admin Interface
      - "7687:7687" # Bolt
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs

  redis:
    image: redis:alpine
    container_name: redis

  worker:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: worker
    command: celery -A celery_app.celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    restart: unless-stopped

  beat:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: beat
    command: celery -A celery_app.celery_app beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  node_modules:
